# Generated by Django 4.0.3 on 2022-03-30 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_remove_items_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.TextField()),
                ('shipping_contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('cancel', 'cancel')], default='pending', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('items_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('cancel', 'cancel')], default='pending', max_length=10)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.transactionheader')),
                ('order', models.ManyToManyField(to='clients.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
